### ISSUE TITLE
[RESEARCH] Drawbacks

### ISSUE THREAD

**Issue by sergeevabc** [claustromaniac/etag-stoppa#1]
Dear @claustromaniac,
Could you be so kind to describe possible drawbacks a user might face using Etag Stoppa extension?

**Comment by claustromaniac** [comment]
Summing them up:
- a negligible impact on performance.
- some console spam (some people can be particular about that).
- stripping `ETag` response headers causes Firefox to not send `If-None-Match` headers (which is the very goal of this extension). If a server expects requests to include `If-None-Match`, since this extension prevents Firefox from sending it, it in turn makes you look more unique to that server. So, this extension eliminates a tracking vector, but raises fingerprinting entropy because of that. This is an acceptable trade-off in my opinion, but there are other solutions that don't have this drawback (like clearing the cache periodically or using the **Temporary Containers** extension).
- not sending `If-None-Match` headers means Firefox will rely on the other caching headers to figure out when a resource has become stale. This means the content will be refreshed in more regular intervals, because the other headers (like `Last-Modified`) use timestamps to set the expiration time. `ETag` is the only header that uses a sort of *versioning* strategy to let clients know when a resource has become stale.

**Comment by sergeevabc** [comment]
It is encouraging to meet a developer who has a full grasp of his subject! Thank you for your time.
