### ISSUE TITLE
console.log=false

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [claustromaniac/etag-stoppa#2]
any chance of adding an option to turn off the console logging? It's rather *f#^king* verbose. Thanks :cat2: 

```js
if (ShutTFUp == false) {
  if (newHeaders.length < d.responseHeaders.length) {
    console.debug(`Removed ETag from request #${d.requestId}\n	${d.url}`);
    return {responseHeaders: newHeaders};
  }
}

```

**Comment by Thorin-II** [comment]
Hey :cat2: , did you get locked in someone's garage again? Hope you're OK :kiss:

**Comment by claustromaniac** [comment]
Your example code would actually break the extension, you just want to remove 
```js
   console.debug(`Removed ETag from request #${d.requestId}\n	${d.url}`);
```
I didn't think it would be much of an issue because I'm dumping that info in the *debug* channel. You can filter that out in the console if you want (there should be a little `debug` button-like thing above). Otherwise (if you're on nightly):
1. download the repo & extract it or whateva
2. remove the aforementioned line
3. zip and install as an extension.

**Comment by Thorin-II** [comment]
It was pseudo code.. anyway .. OMFG .. you escaped the basement .. and there's a new pref that groups console errors, I'll go find it, and also check if your console error is generic and not unique each time

**Comment by Thorin-II** [comment]
I like to see all the output, but yeah, OK, debug ..
