### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by ghost** [claustromaniac/etag-stoppa#3]
Is it possible to add a whitelist in?

**Comment by claustromaniac** [comment]
It is possible. If you don't mind me asking, why would you want one?

**Comment by ghost** [comment]
Trying to cover all bases testing what makes reCAPTCHA spit out the "you might be sending automated requests" error.

**Comment by claustromaniac** [comment]
If I recall correctly, solving multiple captchas quickly is one of the triggers. I believe using Firefox (instead of Chrome) is also a factor. Chrome users have a way easier time with reCAPTCHA. @Thorin-Oakenpants may have some more insight to offer on that.

I'm pretty sure removing `ETag` and some other headers is not a factor. This is just empirical knowledge, but still, to be honest, I've never planned to add any features to this extension. I even disabled the Issues for this repo when I created it, because of that. I enabled it afterwards only in case someone had a question or something to report.
